spring:
  datasource:
    url: jdbc:h2:mem:teste
    username: teste
    password: teste
    driver-class-name: org.h2.Driver
    platform: org.hibernate.dialect.H2Dialect
  jpa:
    open-in-view: true
  devtools:
    add-properties: true
logging:
  level: 
    web: debug