spring:
  datasource:
    username: rafa
    password:
    driver-class-name: org.postgresql.Driver
    platform: org.hibernate.dialect.PostgreSQLDialect
    url: jdbc:postgresql://
  jpa:
    database: postgresql
  flyway:
    enabled: true
  h2:
    console:
      enabled: false
logging:
  level:
    web: info
