create table login
(
    email  varchar primary key,
    senha  varchar,
    perfil varchar
);

create table endereco
(
    id       integer primary key generated BY DEFAULT AS IDENTITY ,
    cep      numeric,
    rua      varchar,
    numero   numeric,
    bairro   varchar,
    detalhes varchar
);

create table ficha
(
    id            integer primary key generated BY DEFAULT AS IDENTITY ,
    duracao       numeric,
    pontuacao     numeric,
    observacoes   varchar,
    nivel         numeric,
    sensibilidade varchar
);

create table terapeuta
(
    id            integer primary key generated BY DEFAULT AS IDENTITY  ,
    nome_completo varchar,
    idade         numeric,
    crp           numeric,
    telefone      varchar,
    cpf           varchar,
    especialidade varchar,
    formacao      varchar,
    id_endereco   integer,
    id_login    varchar,
    foreign key (id_endereco) references endereco (id),
    foreign key (id_login) references login (email)
);

create table paciente
(
    id            integer primary key generated BY DEFAULT AS IDENTITY ,
    nome_completo varchar,
    idade         numeric,
    id_ficha      integer,
    id_terapeuta integer,
    foreign key (id_terapeuta) references terapeuta (id),
    foreign key (id_ficha) references ficha (id)
);

create table responsavel
(
    id            integer primary key generated BY DEFAULT AS IDENTITY ,
    nome_completo varchar,
    idade         numeric,
    telefone      varchar,
    cpf           varchar,
    parentesco    varchar,
    id_endereco integer,
    id_login varchar,
    foreign key (id_endereco) references endereco (id),
    foreign key (id_login) references login (email)
);